CursoMVC5/Models/Bus.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
            this.Viaje = new HashSet<Viaje>();
        }
    
        public int IIDBUS { get; set; }
        public Nullable<int> IIDSUCURSAL { get; set; }
        public Nullable<int> IIDTIPOBUS { get; set; }
        public string PLACA { get; set; }
        public Nullable<System.DateTime> FECHACOMPRA { get; set; }
        public Nullable<int> IIDMODELO { get; set; }
        public Nullable<int> NUMEROFILAS { get; set; }
        public Nullable<int> NUMEROCOLUMNAS { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> IIDMARCA { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoBus TipoBus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viaje> Viaje { get; set; }
    }
}

CursoMVC5/Controllers/BusController.cs
using CursoMVC5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CursoMVC5.Controllers
{
    public class BusController : Controller
    {
        // GET: Bus
        public ActionResult Index()
        {
            List<Bus_CLS> listaBus = null;
            using(var bd = new BDPasajeEntities())
            {
                listaBus = (from bus in bd.Bus
                            join Sucursal in bd.Sucursal
                            on bus.IIDSUCURSAL equals Sucursal.IIDSUCURSAL
                            join TipoBus in bd.TipoBus
                            on bus.IIDTIPOBUS equals TipoBus.IIDTIPOBUS
                            join tipoModelo in bd.Modelo
                            on bus.IIDMODELO equals tipoModelo.IIDMODELO
                            where bus.BHABILITADO ==1

                            select new Bus_CLS
                            {
                                IidBus = bus.IIDBUS,
                                placa = bus.PLACA,
                                NombreModelo = tipoModelo.NOMBRE,
                                NombreSucursal = Sucursal.NOMBRE,
                                NombreTipoBus = TipoBus.NOMBRE

                            }).ToList();
            }
            return View(listaBus);
        }

        public ActionResult Agregar()
        {
			Llenar_Combos();
            return View();
        }

		[HttpPost]

		public ActionResult Agregar(Bus_CLS Bus_cls)
		{

			if(!ModelState.IsValid)
			{
				Llenar_Combos();
				return View(Bus_cls);
			}

			using(var bd= new BDPasajeEntities())
			{
				Bus oBus= new Bus();
				oBus.BHABILITADO = 1;
				oBus.IIDSUCURSAL = Bus_cls.IidSucursal;
				oBus.IIDTIPOBUS = Bus_cls.IidTipoBus;
				oBus.PLACA = Bus_cls.placa;
				oBus.FECHACOMPRA = Bus_cls.FechaCompra;
				oBus.IIDMODELO = Bus_cls.IidModelo;
				oBus.NUMEROFILAS = Bus_cls.NumeroFilas;
				oBus.NUMEROCOLUMNAS = Bus_cls.NumeroColumnas;
				oBus.DESCRIPCION = Bus_cls.Descripcion;
				oBus.OBSERVACION = Bus_cls.Observacion;
				oBus.IIDMARCA = Bus_cls.IidMarca;

				bd.Bus.Add(oBus);
				bd.SaveChanges();
			}
			return RedirectToAction("Index",Bus_cls);
		}


		public void Llenar_Combos()
		{
			listarMarca();
			listarModelo();
			listarSucursal();
			listarTipoBus();
		}


		public void listarTipoBus()
		{
			List<SelectListItem> lista;
			using (var bd = new BDPasajeEntities())
			{
				lista = (from TipoContrato in bd.TipoBus
						 where TipoContrato.BHABILITADO == 1
						 select new SelectListItem
						 {
							 Text = TipoContrato.NOMBRE,
							 Value = TipoContrato.IIDTIPOBUS.ToString(),

						 }).ToList();

				lista.Insert(0, new SelectListItem { Text = "--Selecione--", Value = "" });
				ViewBag.listarTipoBus = lista;
			}
		}

		public void listarMarca()
		{
			List<SelectListItem> lista;
			using (var bd = new BDPasajeEntities())
			{
				lista = (from TipoContrato in bd.Marca
						 where TipoContrato.BHABILITADO == 1
						 select new SelectListItem
						 {
							 Text = TipoContrato.NOMBRE,
							 Value = TipoContrato.IIDMARCA.ToString(),

						 }).ToList();

				lista.Insert(0, new SelectListItem { Text = "--Selecione--", Value = "" });
				ViewBag.listarMarca = lista;
			}
		}

		public void listarModelo()
		{
			List<SelectListItem> lista;
			using (var bd = new BDPasajeEntities())
			{
				lista = (from TipoContrato in bd.Modelo
						 where TipoContrato.BHABILITADO == 1
						 select new SelectListItem
						 {
							 Text = TipoContrato.NOMBRE,
							 Value = TipoContrato.IIDMODELO.ToString(),

						 }).ToList();

				lista.Insert(0, new SelectListItem { Text = "--Selecione--", Value = "" });
				ViewBag.listarModelo = lista;
			}
		}

		public void listarSucursal()
		{
			List<SelectListItem> lista;
			using (var bd = new BDPasajeEntities())
			{
				lista = (from TipoContrato in bd.Sucursal
						 where TipoContrato.BHABILITADO == 1
						 select new SelectListItem
						 {
							 Text = TipoContrato.NOMBRE,
							 Value = TipoContrato.IIDSUCURSAL.ToString(),

						 }).ToList();

				lista.Insert(0, new SelectListItem { Text = "--Selecione--", Value = "" });
				ViewBag.listarSucursal = lista;
			}
		}

		[HttpGet]
		public ActionResult Editar(int IidBus)
		{
			Bus_CLS bus_CLS = new Bus_CLS();
						
			using (var bd = new BDPasajeEntities())
			{
				Bus bus = bd.Bus.Where(p => p.IIDBUS.Equals(IidBus)).First();			

				bus_CLS.IidSucursal = (int)bus.IIDSUCURSAL;
				bus_CLS.placa = bus.PLACA;
				bus_CLS.FechaCompra = (DateTime)bus.FECHACOMPRA;
				bus_CLS.IidModelo = (int)bus.IIDMODELO;
				bus_CLS.NumeroColumnas = (int)bus.NUMEROCOLUMNAS;
				bus_CLS.NumeroFilas = (int)bus.NUMEROFILAS;
				bus_CLS.Descripcion = bus.DESCRIPCION;
				bus_CLS.Observacion = bus.OBSERVACION;
				bus_CLS.IidMarca = (int)bus.IIDMARCA;
				
			}
			Llenar_Combos();
			return View(bus_CLS);
		}

		[HttpPost]
		public ActionResult Editar(Bus_CLS obus)
		{
			if (!ModelState.IsValid)
			{
				return View(obus);
			}

			int id = obus.IidBus;
			using(var bd = new BDPasajeEntities())
			{
				Bus bus = bd.Bus.Where(p => p.Equals(id)).First();

				bus.IIDSUCURSAL = obus.IidSucursal;
				bus.PLACA = obus.placa;
				bus.FECHACOMPRA = obus.FechaCompra;
				bus.IIDMODELO = obus.IidModelo;
				bus.NUMEROCOLUMNAS = obus.NumeroColumnas;
				bus.NUMEROFILAS = obus.NumeroFilas;
				bus.DESCRIPCION = obus.Descripcion;
				bus.OBSERVACION = obus.Observacion;
				bus.IIDMARCA = obus.IidMarca;

				bd.SaveChanges();
			}
			return RedirectToAction("Index");
		}


	}
}

CursoMVC5/Views/Bus/Agregar.cshtml
@model CursoMVC5.Models.Bus_CLS

@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> listaTipoBus = (List<SelectListItem>)ViewBag.listarTipoBus;
    List<SelectListItem> listaMarca = (List<SelectListItem>)ViewBag.listarMarca;
    List<SelectListItem> listaModelo = (List<SelectListItem>)ViewBag.listarModelo;
    List<SelectListItem> listaSucursal = (List<SelectListItem>)ViewBag.listarSucursal;


}

<h2>Agregar</h2>

@using (Html.BeginForm("Agregar","Bus",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bus_CLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      

        <div class="form-group">
            @Html.LabelFor(model => model.IidSucursal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownList("IidSucursal", listaSucursal, new {  @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.IidSucursal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IidTipoBus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IidTipoBus", listaTipoBus, new  { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.IidTipoBus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.placa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.placa, new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.placa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCompra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCompra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCompra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IidModelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IidModelo", listaMarca,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.IidModelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroFilas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroFilas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroFilas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroColumnas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroColumnas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroColumnas, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Observacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IidMarca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IidMarca", listaMarca, new  { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.IidMarca, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CursoMVC5/Views/Bus/Editar.cshtml
@model CursoMVC5.Models.Bus_CLS

@{
    ViewBag.Title = "Editar";
    List<SelectListItem> listaTipoBus = (List<SelectListItem>)ViewBag.listarTipoBus;
    List<SelectListItem> listaMarca = (List<SelectListItem>)ViewBag.listarMarca;
    List<SelectListItem> listaModelo = (List<SelectListItem>)ViewBag.listarModelo;
    List<SelectListItem> listaSucursal = (List<SelectListItem>)ViewBag.listarSucursal;


}

<h2>Editar</h2>

@using (Html.BeginForm("Agregar", "Bus", FormMethod.Post, new { @id = "frmBus" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bus_CLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.IidSucursal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IidSucursal", listaSucursal, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IidSucursal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IidTipoBus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IidTipoBus", listaTipoBus, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IidTipoBus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.placa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.placa, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.placa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCompra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCompra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCompra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IidModelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IidModelo", listaMarca, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IidModelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroFilas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroFilas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroFilas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroColumnas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroColumnas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroColumnas, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Observacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IidMarca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IidMarca", listaMarca, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IidMarca, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Guardar
            </button>
            @Html.ActionLink("Regresar", "Index", "Bus", null, new { @class = "btn btn-danger" })
        </div>
    </div>
}

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Desea guardar los cambios?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Aceptar()" class="btn btn-primary">Aceptar</button>
            </div>
        </div>
    </div>
</div>

<script>


    function Aceptar() {
        var frmBus = document.getElementById("frmBus")
        frmBus.submit();
    }

</script>

CursoMVC5/Views/Bus/Index.cshtml
@using CursoMVC5.Models
@model List<Bus_CLS>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@Html.ActionLink("Agregar", "Agregar", "Bus", new {@class="btn"})

<div class="container"
    <div class="row mt-3">
        <div class="col">
            <table class="table table-bordered table-hover">
                <thead class="table-primary">
                    <tr>
                        <td>@Html.LabelFor(p => p[0].IidBus)</td>
                        <td>@Html.LabelFor(p => p[0].placa)</td>
                        <td>@Html.LabelFor(p => p[0].NombreModelo)</td>
                        <td>@Html.LabelFor(p => p[0].NombreSucursal)</td>
                        <td>@Html.LabelFor(p => p[0].NombreTipoBus)</td>
                        <td>Operaciones</td>
                    </tr>
                </thead>
                <tbody class="text-center table-striped-columns ">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.IidBus</td>
                            <td>@item.placa</td>
                            <td>@item.NombreModelo</td>
                            <td>@item.NombreSucursal</td>
                            <td>@item.NombreTipoBus</td>
                            <td>
                                @Html.ActionLink("Editar", "Editar", "Bus",new { item.IidBus }, new { @class = "btn btn-primary" })
                                @Html.ActionLink("Editar", "Eliminar", "Bus", @item.IidBus, new { @class = "btn btn-danger" })


                            </td>
                        </tr>
                    }

                </tbody>


            </table>



        </div>
    </div>
</div>