CursoMVC5/Models/Viaje.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.Asiento = new HashSet<Asiento>();
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
        }
    
        public int IIDVIAJE { get; set; }
        public Nullable<int> IIDLUGARORIGEN { get; set; }
        public Nullable<int> IIDLUGARDESTINO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> FECHAVIAJE { get; set; }
        public Nullable<int> IIDBUS { get; set; }
        public Nullable<int> NUMEROASIENTOSDISPONIBLES { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public byte[] FOTO { get; set; }
        public string nombrefoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual Lugar Lugar1 { get; set; }
    }
}

CursoMVC5/Controllers/ViajeController.cs
using CursoMVC5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CursoMVC5.Controllers
{
    public class ViajeController : Controller
    {
        // GET: Viaje
        public ActionResult Index()
        {
            List<Viaje_CLS> listaViaje = null;

            using (var bd = new BDPasajeEntities())
            {
                listaViaje = (from Viaje in bd.Viaje
                              join lugarOrigen in bd.Lugar
                              on Viaje.IIDLUGARORIGEN equals lugarOrigen.IIDLUGAR
                              join LugarDestino in bd.Lugar
                              on Viaje.IIDLUGARDESTINO equals LugarDestino.IIDLUGAR
                              join bus in bd.Bus
                              on Viaje.IIDBUS equals bus.IIDBUS
                              select new Viaje_CLS
                              {
                                  iidviaje = Viaje.IIDVIAJE,
                                  nombreBus = bus.PLACA,
                                  nombreLugarOrigen = lugarOrigen.NOMBRE,
                                  nombreLugarDestino = LugarDestino.NOMBRE

                              }).ToList();
            }

            return View(listaViaje);
        }

        public void llenarCombos()
        {
            ListarBus();
            ListarLugar();
        }

        public void ListarLugar()
        {
            List<SelectListItem> list;
            using (var bd = new BDPasajeEntities())
            {
                list = (from item in bd.Lugar
                        where item.BHABILITADO == 1
                        select new  SelectListItem
                        {
                            Text = item.NOMBRE,
                            Value = item.IIDLUGAR.ToString()
                        }).ToList();
                list.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaLugar = list;
            }
        }

		public void ListarBus()
		{
			List<SelectListItem> list;
			using (var bd = new BDPasajeEntities())
			{
				list = (from item in bd.Bus
						where item.BHABILITADO == 1
						select new SelectListItem
						{
							Text = item.PLACA,
							Value = item.IIDBUS.ToString()
						}).ToList();
				list.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
				ViewBag.listaBus = list;
			}
		}

		public ActionResult Agregar(Viaje_CLS oViaje)
        {
            llenarCombos();
            return View();

        }
        
    }
}

CursoMVC5/Views/Viaje/Agregar.cshtml
@model CursoMVC5.Models.Viaje_CLS

@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> listaBus = (List<SelectListItem>)ViewBag.listaBus;
    List<SelectListItem> listaLugar = (List<SelectListItem>)ViewBag.listaLugar;

}
<h2>Agregar</h2>

@using (Html.BeginForm("Agregar", "Agregar","Viaje",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Viaje_CLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarOrigen", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarOrigen", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaViaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaViaje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaViaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidbus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarOrigen", listaBus, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidbus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numeroDeAsientos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroDeAsientos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroDeAsientos, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.nombreBus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombreBus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombreBus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Regresar", "Index", "viaje", null, new {@class ="btn btn-danger"})
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CursoMVC5/Views/Viaje/Index.cshtml
@using CursoMVC5.Models
@model List<Viaje_CLS>
@{
    ViewBag.Title = "Index";
}

<h2>Viaje Index</h2>

@Html.ActionLink("Agregar", "Agregar", "viaje", null, new { @class = "btn btn-primary" })

<div class="container mt-3">
    <div class="row">
        <div class="col">
            <table class="table table-borderless table-hover table-striped">
                <thead class="table-dark">
                    <tr>
                        <td>@Html.LabelFor(p => p[0].iidviaje)</td>
                        <td>@Html.LabelFor(p => p[0].nombreLugarOrigen)</td>
                        <td>@Html.LabelFor(p => p[0].nombreLugarDestino)</td>
                        <td>@Html.LabelFor(p => p[0].nombreBus)</td>
                        <td>Operaciones</td>
                    </tr>
                </thead>
                <tbody class="table-striped">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.iidviaje</td>
                            <td>@item.nombreLugarOrigen</td>
                            <td>@item.nombreLugarDestino</td>
                            <td>@item.nombreBus</td>
                            <td>
                                @Html.ActionLink("Editar", "Editar", "viaje", new { id = item.iidviaje }, new { @class = "btn btn-primary" })
                                @Html.ActionLink("Borrar", "Borrar", "viaje", new { id = item.iidviaje }, new { @class = "btn btn-danger" })

                            </td>
                        </tr>

                    }

                </tbody>
            </table>
        </div>
    </div>
</div>