CursoMVC5/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDMARCA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

CursoMVC5/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using CursoMVC5.Models;

namespace CursoMVC5.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index()
        {
            List<Marca_CLS> listaMarca = null;

			using (var bd = new BDPasajeEntities())
            {
                listaMarca =( from marca in bd.Marca 
                              where marca.BHABILITADO == 1
                                             select new Marca_CLS

                                             {
                                                 iidMarca=marca.IIDMARCA,
                                                 nombre=marca.NOMBRE,
                                                 descripcion=marca.DESCRIPCION

                                             }).ToList();
            }

            return View(listaMarca);
        }
        [HttpGet]

        public ActionResult Agregar()
        {
			
			return View();
		}

        [HttpPost]
		public ActionResult Agregar(Marca_CLS marca)
		{
            int num_registros = 0;
            string nom_marca = marca.nombre;
            using(var bd = new BDPasajeEntities())
            {
                num_registros= bd.Marca.Where(p=>p.NOMBRE.Equals(nom_marca)).Count();
            }

			if (!ModelState.IsValid || num_registros != 0 )
			{
                if (num_registros != 0) marca.mensaje_error = $"El nombre {marca.nombre} ya existe";
				return View(marca);
            }
            else
            {
                using (var bd = new BDPasajeEntities())
                {
					Marca oMarca = new Marca();
                    oMarca.NOMBRE = marca.nombre;
                    oMarca.DESCRIPCION = marca.descripcion;
                    oMarca.BHABILITADO = 1;
                    bd.Marca.Add(oMarca);
                    bd.SaveChanges();
                    
				}
                    
            }
			return RedirectToAction("Index");
		}


        public ActionResult Editar(int id)
        {           

            Marca_CLS oMarca_CLS = new Marca_CLS();
            using(var bd = new BDPasajeEntities())
            {
                Marca oMarca = bd.Marca.Where(p =>p.IIDMARCA.Equals(id)).First();
				oMarca_CLS.iidMarca = oMarca.IIDMARCA;
				oMarca_CLS.nombre = oMarca.NOMBRE;
				oMarca_CLS.descripcion = oMarca.DESCRIPCION;
			}

            return View(oMarca_CLS);
        }

        [HttpPost]
        public ActionResult Editar(Marca_CLS oMarca_CLS)
        {
			int num_registros = 0;
			string nom_marca = oMarca_CLS.nombre;
            int id = oMarca_CLS.iidMarca;
			using (var bd = new BDPasajeEntities())
			{
				num_registros = bd.Marca.Where(p => p.NOMBRE.Equals(nom_marca) && !p.IIDMARCA.Equals(id)).Count();
			}


            if (!ModelState.IsValid || num_registros >= 1) oMarca_CLS.mensaje_error = "ya se emcuentra registrada la marca";
            {
                if(num_registros >=1)
                return View(oMarca_CLS);
            }

            int idMarca = oMarca_CLS.iidMarca;
            using (var bd = new BDPasajeEntities())
            {
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(idMarca)).First();
                oMarca.NOMBRE = oMarca_CLS.nombre;
				oMarca.DESCRIPCION = oMarca_CLS.descripcion;
                bd.SaveChanges();
			}

            return RedirectToAction("Index");

        }

        
        public ActionResult Eliminar(int id)
        {
            using(var bd = new BDPasajeEntities())
            {
                Marca oMarca = bd.Marca.Where(p => p.IIDMARCA.Equals(id)).First();
                oMarca.BHABILITADO = 0;
                bd.SaveChanges();
            }

            return RedirectToAction("Index");

        }
	}
}

CursoMVC5/Views/Marca/Agregar.cshtml
@using CursoMVC5
@model CursoMVC5.Models.Marca_CLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>


    <div class="row">
        <div class="col-md-6">
            @using (Html.BeginForm("Agregar", "Marca", FormMethod.Post))
            {
                <div>
                    @Html.LabelFor(p => p.nombre, new { @class = "w-100" })

                    @Html.TextBoxFor(P => P.nombre, new { @class = "from-control w-100" })
                    @Html.ValidationMessage("nombre",new {@class="text-danger"})
                    @if (Model!=null && Model.mensaje_error != null)
                    {
                        @Html.Label(Model.mensaje_error, new {@class="text-danger"})
                    }


                </div>
                <div>
                    @Html.LabelFor(p => p.descripcion, new { @class = "w-100" })
                    @Html.TextBoxFor(P => P.descripcion, new { @class = "from-control w-100" })
                    @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
                </div>
               
                <br />
                <div>
                    <input type="submit" class="btn btn-primary" value="Guardar" />
                </div>


            }
        </div>
    </div>

CursoMVC5/Views/Marca/Editar.cshtml
@using CursoMVC5.Models
@model Marca_CLS

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Marca</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Marca", FormMethod.Post, new {@id="formEditar"}))
        {

            <div>
                @Html.LabelFor(p => p.iidMarca, new { @class = "w-100" ,@readOnly=true })
                @Html.TextBoxFor(P => P.iidMarca, new { @class = "from-control w-100" })
                @Html.ValidationMessage("iidMarca", new { @class = "text-danger" })
            </div>

            <div>
                @Html.LabelFor(p => p.nombre, new { @class = "w-100" })
                @Html.TextBoxFor(P => P.nombre, new { @class = "from-control w-100" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model != null && Model.mensaje_error != null)
                {
                    @Html.Label(Model.mensaje_error, new { @class = "text-danger" })
                }
            </div>
            <div>
                @Html.LabelFor(p => p.descripcion, new { @class = "w-100" })
                @Html.TextBoxFor(P => P.descripcion, new { @class = "from-control w-100" })
                @Html.ValidationMessage("descripcion", new { @class = "text-danger" })
            </div>

            <br />
            <div>
                <input type="submit" class="btn btn-primary" value="Guardar" />

                @Html.ActionLink("Regresar", "Index", "Marca", null, new { @class = "btn btn-primary mb-3" })
            </div>


        }
    </div>
</div>

<script>
    var frmEditar = document.getElementById("formEditar");
    frmEditar.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("Deseas guardar los cambios?") == 1) {
            frmEditar.submit();
        }

    }

</script>

CursoMVC5/Views/Marca/Index.cshtml
@using CursoMVC5.Models
@model List<Marca_CLS>
@{
    ViewBag.Title = "Index";

}

<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<h2>Index</h2>

@Html.ActionLink("Agregar", "Agregar", "Marca", null, new { @class = "btn btn-primary mb-3" })

<table class="table table-bordered ">
    <thead class="table-danger table-hover">
        <tr>
            <td width="10%">@Html.LabelFor(p => Model[0].iidMarca)</td>
            <td width="20%">@Html.LabelFor(p => Model[0].nombre)</td>
            <td width="60%">@Html.LabelFor(p => Model[0].descripcion)</td>
            <td width="10%">Operaciones</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="10%">@item.iidMarca</td>
                <td width="15%">@item.nombre</td>
                <td>@item.descripcion</td>
                <td class="text-center">
                    @Html.ActionLink("🖋️", "Editar", "Marca", new { id = @item.iidMarca }, new { @class = "fa-solid fa-pen-to-square" })               

                    
                    @Html.ActionLink("🚮", "Eliminar", "Marca", new { id = @item.iidMarca }, new { @class = "glyphicon glyphicon-trash" ,@onclick="eliminar()"})
                </td>

            </tr>

        }
    </tbody>

</table>

<script>

    function eliminar() {
        if (confirm("Desea eliminar el reciobi correctamente") == 1) {
            alert("Se elimino coreectamente")
        } else {
            event.preventDefault();

        }
    }

</script>