CursoMVC5/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

CursoMVC5/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CursoMVC5.Models;

namespace CursoMVC5.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index()
        {
            List<Sucursal_CLS> listaSucursal = new List<Sucursal_CLS>();
            using (var bd = new BDPasajeEntities())
            {
                listaSucursal = (from Sucursal in bd.Sucursal
                                 where Sucursal.BHABILITADO == 1
                                 select new Sucursal_CLS
                                 {
                                     Iidsucursal = Sucursal.IIDSUCURSAL,
                                     Nombre = Sucursal.NOMBRE,
                                     Telefono = Sucursal.TELEFONO,
                                     Email = Sucursal.EMAIL

                                 }).ToList();
            }
            return View(listaSucursal);
        }

        [HttpGet]
        public ActionResult Agregar()
        {

            return View();
        }

        [HttpPost]

        public ActionResult Agregar(Sucursal_CLS oSucursalCLS)
        {
            int num_registros = 0;
            string nom = oSucursalCLS.Nombre;
            using(var bd = new BDPasajeEntities())
            {
                num_registros = bd.Sucursal.Where(p=>p.NOMBRE.Equals(nom)).Count();
            }

            if (ModelState.IsValid || num_registros !=0)
            {
                oSucursalCLS.Msg_error = "la sucursal que deceas agregar ya existe ";
                return View(oSucursalCLS);
            }

            using (var bd = new BDPasajeEntities())
            {
				Sucursal oSucursal = new Sucursal
				{
					NOMBRE = oSucursalCLS.Nombre,
					DIRECCION = oSucursalCLS.Direccion,
					TELEFONO = oSucursalCLS.Telefono,
					EMAIL = oSucursalCLS.Email,
					FECHAAPERTURA = oSucursalCLS.FechaApertura
			    };
				
                oSucursal.BHABILITADO = 1;
                bd.Sucursal.Add(oSucursal);
                bd.SaveChanges();
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Editar(int id)
        {
            Sucursal_CLS sucursalCLS = new Sucursal_CLS();

            using(var bd = new BDPasajeEntities())
            {
                Sucursal osucursal = bd.Sucursal.Where( p=> p.IIDSUCURSAL.Equals(id)).First();
				sucursalCLS.Iidsucursal = osucursal.IIDSUCURSAL;
				sucursalCLS.Nombre = osucursal.NOMBRE;
				sucursalCLS.Direccion = osucursal.DIRECCION;
				sucursalCLS.Telefono = osucursal.TELEFONO;
				sucursalCLS.Email = osucursal.EMAIL;
                sucursalCLS.FechaApertura = (DateTime)osucursal.FECHAAPERTURA;
				

			}

            return View(sucursalCLS);
        }

        [HttpPost]
        public ActionResult Editar(Sucursal_CLS oSucursal)
        {
            if (!ModelState.IsValid)
            {
                return View(oSucursal);
            }
            int id = oSucursal.Iidsucursal;

            using(var bd=new BDPasajeEntities())
            {
                Sucursal sucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();

                sucursal.NOMBRE = oSucursal.Nombre;
				sucursal.DIRECCION = oSucursal.Direccion;
				sucursal.TELEFONO = oSucursal.Telefono;
				sucursal.EMAIL = oSucursal.Email;
				sucursal.FECHAAPERTURA = oSucursal.FechaApertura;
                
                bd.SaveChanges();
			}

            return RedirectToAction("Index");
        }


        public ActionResult Eliminar(int id)
        {
            using(var bd  = new BDPasajeEntities())
            {
                Sucursal osucursal = bd.Sucursal.Where(p=>p.Equals(id)).First();
                osucursal.BHABILITADO = 0;
                bd.SaveChanges();
            }

            return RedirectToAction("Index");

        }


	}
}

CursoMVC5/Views/Sucursal/Agregar.cshtml
@using CursoMVC5.Models
@model Sucursal_CLS

@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

@using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post, new {@id= "formSucursal" }))
{
    <div class="container mt-3">
        <div class="row">
            @Html.LabelFor(p => p.Nombre)
            @Html.TextBoxFor(p => p.Nombre, new { @class = "form-control" })
            @Html.ValidationMessage("Nombre", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.Direccion)
            @Html.TextBoxFor(p => p.Direccion, new { @class = "form-control" })
            @Html.ValidationMessage("Direccion", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.Telefono)
            @Html.TextBoxFor(p => p.Telefono, new { @class = "form-control" })
            @Html.ValidationMessage("Telefono", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.Email)
            @Html.TextBoxFor(p => p.Email, new { @class = "form-control" })
            @Html.ValidationMessage("Email", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.FechaApertura)
            @Html.EditorFor(p => p.FechaApertura, new { @class = "form-control" })
            @Html.ValidationMessage("Fecha de Apertura", new { @class = "text-danger" })

        </div>

        <div class="row mt-5">

            <input type="submit" name="AgregarSucursal" value="Agregar Sucursal" class="btn btn-outline-primary" />

        </div>
    </div>
}



<script>
    var formSucursal = document.getElementById("formSucursal");
    formSucursal.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("quieres guardar los cambios") == 1) {
            formSucursal.submit()
        }
    }
</script>

CursoMVC5/Views/Sucursal/Editar.cshtml
@using CursoMVC5.Models
@model Sucursal_CLS

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Sucursal</h2>

@using (Html.BeginForm("Editar", "Sucursal", FormMethod.Post, new {@id="formSucursal"} ))
{
    <div class="container mt-3">
        <div class="row">
            @Html.LabelFor(p => p.Iidsucursal)
            @Html.TextBoxFor(p => p.Iidsucursal, new { @class = "form-control, readOnly=true" })
            @Html.ValidationMessage("Iidsucursal", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.Nombre)
            @Html.TextBoxFor(p => p.Nombre, new { @class = "form-control" })
            @Html.ValidationMessage("Nombre", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.Direccion)
            @Html.TextBoxFor(p => p.Direccion, new { @class = "form-control" })
            @Html.ValidationMessage("Direccion", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.Telefono)
            @Html.TextBoxFor(p => p.Telefono, new { @class = "form-control" })
            @Html.ValidationMessage("Telefono", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.Email)
            @Html.TextBoxFor(p => p.Email, new { @class = "form-control" })
            @Html.ValidationMessage("Email", new { @class = "text-danger" })

        </div>

        <div class="row">
            @Html.LabelFor(p => p.FechaApertura)
            @Html.EditorFor(p => p.FechaApertura, new { @class = "form-control" })
            @Html.ValidationMessage("Fecha de Apertura", new { @class = "text-danger" })

        </div>

        <div class="row mt-5">

            <input type="submit" name="AgregarSucursal" value="Editar Sucursal" class="btn btn-outline-warning" />
            @Html.ActionLink("Regresar", "Index", "sucursal", null, new { @class = "btn btn-danger" })
        </div>
    </div>
}


<script>
    var formSucursal = document.getElementById("formSucursal");
    formSucursal.onsubmit = function (e) {
        e.preventDefault();
        if (confirm("quieres guardar los cambios") == 1) {
            formSucursal.submit()
        }
    }
</script>

CursoMVC5/Views/Sucursal/Index.cshtml
@using CursoMVC5.Models
@model List<Sucursal_CLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("Agregar","Agregar","Sucursal",null , new {@class= "btn btn-primary"})

<table class="table mt-3">
    <thead class="table-dark">
        <tr>
            <td>@Html.LabelFor(p => Model[0].Iidsucursal)</td>
            <td>@Html.LabelFor(p => Model[0].Nombre)</td>
            <td>@Html.LabelFor(p => Model[0].Telefono)</td>
            <td>@Html.LabelFor(p => Model[0].Email)</td>
            <td>Operaciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Iidsucursal</td>
                <td>@item.Nombre</td>
                <td>@item.Telefono</td>
                <td>@item.Email</td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = @item.Iidsucursal }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = @item.Iidsucursal }, new { @class = "btn btn-warning" ,@onclick="eliminarSucursal()"})

                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    function eliminarSucursal() {
        if (confirm("Deceas eliminar") == 1) {
            alert("Se elimino")
        } else {
            event.preventDefault();
        }
    }

</script>